-- =====================================================
-- STEP 10 (Revised): Ensure ALL Units exist
-- =====================================================
INSERT IGNORE INTO portal_units (id, name, created_at) VALUES 
(UUID(), 'Abul Fazl Enclave North', NOW()),
(UUID(), 'Abul Fazl Enclave South', NOW()),
(UUID(), 'Ballimaran', NOW()),
(UUID(), 'Bara Hindu Rao', NOW()),
(UUID(), 'Batla House', NOW()),
(UUID(), 'Chhajarsi', NOW()),
(UUID(), 'Ghonda', NOW()),
(UUID(), 'Greater Noida', NOW()),
(UUID(), 'Inderlok', NOW()),
(UUID(), 'Indrapuri', NOW()),
(UUID(), 'Jahangir Puri', NOW()),
(UUID(), 'Jaitpur', NOW()),
(UUID(), 'Jamia hamdard', NOW()),
(UUID(), 'Jasola', NOW()),
(UUID(), 'Kanchankunj', NOW()),
(UUID(), 'Kardampuri', NOW()),
(UUID(), 'Karol Bagh', NOW()),
(UUID(), 'Loni', NOW()),
(UUID(), 'Mahipalpur', NOW()),
(UUID(), 'Nabi Karim', NOW()),
(UUID(), 'New Mustafabad', NOW()),
(UUID(), 'Nihal Vihar', NOW()),
(UUID(), 'Okhla Village', NOW()),
(UUID(), 'Old Mustafabad', NOW()),
(UUID(), 'Pasonda', NOW()),
(UUID(), 'Raghubir Nagar', NOW()),
(UUID(), 'Saket', NOW()),
(UUID(), 'Seemapuri', NOW()),
(UUID(), 'Shahdara', NOW()),
(UUID(), 'Shaheen Bagh', NOW()),
(UUID(), 'shakurpur', NOW()),
(UUID(), 'Usmanpur', NOW()),
(UUID(), 'Vijay Nagar', NOW()),
(UUID(), 'Vikas Nagar', NOW());

-- =====================================================
-- STEP 11: Link Members to Units/Campuses
-- =====================================================
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdur Rehman Ahmed' OR (phone = '9266151258' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Maaz Khalid' OR (phone = '9315215814' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Umar' OR (phone = '7080197521' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mujtabullah Falahi' OR (phone = '7870469990' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Anas' OR (phone = '7974268844' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Shahed Ahmed' OR (phone = '9810479879' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Suhaib Ahmed' OR (phone = '8496812360' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zuhair Ahmed Shaikh' OR (phone = '7569897999' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Qadar' OR (phone = '8446328178' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abul Kalam khan' OR (phone = '9650452891' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Fauzan Ghazi' OR (phone = '9582862894' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Furqan Abid' OR (phone = '7406182900' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Imran Khan' OR (phone = '9927104282' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Miqdad' OR (phone = '9559156358' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Moaz Bin Asad' OR (phone = '7292886536' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Danish' OR (phone = '9971664117' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Maaz Inam' OR (phone = '9717138500' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Saad Inam' OR (phone = '7982478661' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Haris Ansari' OR (phone = '7836828541' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sheikh Rahil' OR (phone = '7083591559' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Yousuf Ahmed' OR (phone = '9560282141' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zakariya' OR (phone = '7558378161' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rehan Fazal' OR (phone = '9205809739' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Azhar Ansar' OR (phone = '8209009629' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abuzar' OR (phone = '7619051030' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Zawwar' OR (phone = '9919550755' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shaikh Luqman' OR (phone = '9096309493' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shaikh Mohammed Kamran' OR (phone = '8626070027' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'ABDUL RAHMAN SADIQ' OR (phone = '8129602103' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave North' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Farrukh Akhtar' OR (phone = '9681886644' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdullah Ammar' OR (phone = '9971074742' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Emad Naeem' OR (phone = '9871653143' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Faheem' OR (phone = '7356234030' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Huzaifa' OR (phone = '8791731019' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Aftab Alam' OR (phone = '7217740052' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Muzammil' OR (phone = '8076344311' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Muhammad Anas Bastavi' OR (phone = '7836802832' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shuja Nabeel' OR (phone = '9997099225' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MD DILKHUSH' OR (phone = '9355254498' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Jawed Alam' OR (phone = '9625600183' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Qadir' OR (phone = '9910206038' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Adnan Shakeel Ahmed' OR (phone = '8447097627' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ahmed Naeem' OR (phone = '9315098257' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ahmed Qasim' OR (phone = '9549549897' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Anas Abbad' OR (phone = '8271757174' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hamza Irfan' OR (phone = '7065960630' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Inzamam' OR (phone = '7011773651' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Abdur Razzaq' OR (phone = '9465151107' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nabeel Anwar' OR (phone = '9540678696' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Salman Khan' OR (phone = '9911466381' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sami Ahmed' OR (phone = '8125961947' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saqib' OR (phone = '9958793481' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saqib Khan' OR (phone = '9560417190' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shumail Yusuf' OR (phone = '7042758566' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Syed Salimullah' OR (phone = '7250705567' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdullah Baig' OR (phone = '8340758620' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'FURQAN KHAN' OR (phone = '9870437879' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'HARIS AMEEN' OR (phone = '9318458946' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'SYED NOOR NAWAZ' OR (phone = '7217649628' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD ASHBAN' OR (phone = '7011082962' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'UMAR ASGAR' OR (phone = '8700518253' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'ARSH AHMED' OR (phone = '9911960383' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Asif Iqbal Tanha' OR (phone = '8595198789' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Abul Fazl Enclave South' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ibrahim Khan' OR (phone = '6387577040' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ballimaran' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Owais' OR (phone = '8505976433' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Bara Hindu Rao' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Wahabul Qumar' OR (phone = '7217861411' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Osaid' OR (phone = '8172945646' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Fawwaz Jawed Khan' OR (phone = '8296148565' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ali Hasan' OR (phone = '9354789914' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ausaf Ayaz' OR (phone = '9099599843' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Kaif Ayaz' OR (phone = '9891945382' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Khubaib Ashraf Khan' OR (phone = '9923957195' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Kashif Tabrez Sheikh' OR (phone = '6375257651' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Muhammad Mujtaba' OR (phone = '7838321660' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rakey Kirmani' OR (phone = '8887519095' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shaeque' OR (phone = '7011280493' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Aizaz Hasan' OR (phone = '9643750134' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Batla House' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'AHMAR' OR (phone = '9310203243' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Chhajarsi' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md. Ruman' OR (phone = '9152308820' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Chhajarsi' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Usman' OR (phone = '9891312325' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammed Nishan K' OR (phone = '9645147785' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nazmuddin Talukdar' OR (phone = '7005963363' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nabeel Mohammed K S' OR (phone = '7592827743' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Najwan MC' OR (phone = '8089856115' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rabeeh' OR (phone = '9447408932' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Althaf' OR (phone = '9400131909' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zakir' OR (phone = '8861719085' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Yasir' OR (phone = '7027731501' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ahfas Ahmed' OR (phone = '9745956747' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ali Muhsin' OR (phone = '8113995179' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Azeem Shan' OR (phone = '9447181147' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammed Athif' OR (phone = '9961366065' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Najih' OR (phone = '8714299774' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sayyed Mohammad Adhil' OR (phone = '8590171161' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sharique Iqbal' OR (phone = '9504283827' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Syed Mohammed Mustafa' OR (phone = '9553938890' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Yaseen Muhammed' OR (phone = '9048806428' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Raies' OR (phone = '9188619700' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ejaj' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'D.U' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'ADHIL NASEEM' OR (phone = '8851431350' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Almas Aamish' OR (phone = '9319802172' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Alnoor Shamish' OR (phone = '9717157202' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Zulkifl' OR (phone = '8929092747' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md. Kashif' OR (phone = '8929092747' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Sameer Saifi' OR (phone = '8585946555' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nasar Ahmed' OR (phone = '9958701106' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Ghonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdullah Umar' OR (phone = '9667379327' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Greater Noida' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sheikh Abid' OR (phone = '9970631362' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Greater Noida' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hamid Anwar' OR (phone = '7654289165' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Greater Noida' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Asjad' OR (phone = '8840107430' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Greater Noida' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Safeer Alam' OR (phone = '8707397876' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'IIISR' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Imam iftekhar' OR (phone = '8603020444' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'IIISR' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Khan Nauman Aadil' OR (phone = '7709455510' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'IIISR' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sajid Ali' OR (phone = '7999921223' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'IIISR' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hashim Sayed Kamran' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'IIISR' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Soban Ahmad' OR (phone = '9079509104' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'IIISR' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Farhan Ahsan Kittur' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Inderlok' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Abdullah' OR (phone = '9315236893' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Indrapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Affan Zahoor Karel' OR (phone = '9028028689' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Noor Aalam' OR (phone = '7678167627' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sheikh Amir' OR (phone = '9266402221' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shekh Abdul Mateen' OR (phone = '8750321601' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Kareem' OR (phone = '9953797080' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Muttalib' OR (phone = '7840037796' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sheikh Rafizul' OR (phone = '9654580742' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jahangir Puri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shekh Saiful Islam' OR (phone = '7291861494' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zaid Choudhary' OR (phone = '9718672037' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zaid Khan' OR (phone = '8714187947' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Aris Khan' OR (phone = '9310487906' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ata Ur Rahman' OR (phone = '9990536320' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md. Sajid Alam' OR (phone = '7289949362' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Danish' OR (phone = '8009277652' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD SHAHID' OR (phone = '8920039966' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'KALIM' OR (phone = '9625737028' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD JUNAID SALMANI' OR (phone = '8882562061' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MD RASHID SHAIKH' OR (phone = '9711050736' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jaitpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'ARHAN AHMED' OR (phone = '9503331882' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Hamdard' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Faizur Rahman' OR (phone = '9795481968' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Hamdard' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hasan Khalid' OR (phone = '8601964801' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jamia hamdard' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nabeel Ahmed' OR (phone = '9984093187' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdullah Mahmood' OR (phone = '9430242035' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hafiz Saeed Kottakal' OR (phone = '9745680274' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hassan Hashmi' OR (phone = '7870966541' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Intekhab' OR (phone = '7280959409' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Asad' OR (phone = '8382009975' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammed Sahal' OR (phone = '9074940687' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Sajid Ansari' OR (phone = '8709108154' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shafaf Murad' OR (phone = '9526628544' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Syed Ilham Jafri' OR (phone = '7902079142' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Tufail Ahmad' OR (phone = '9852056349' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zaki Nafees' OR (phone = '9634199593' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Intekhab' OR (phone = '8271862589' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Majid' OR (phone = '9304332130' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abu Salim Yahiya' OR (phone = '7275446566' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abul Ahla' OR (phone = '9605743433' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ahmad Saeed' OR (phone = '8429077406' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ashiq Marjaan' OR (phone = '9446521601' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Asif Javed' OR (phone = '8127308303' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Hammadur Rahman' OR (phone = '7428627930' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Huzaifa Humam Ahsan' OR (phone = '9955274545' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Jiyad Muhammed' OR (phone = '9497216515' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Khan Tahir' OR (phone = '9920657458' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Shadab Quaraishi' OR (phone = '6289404754' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mishal EP' OR (phone = '8078572378' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammed Safwan' OR (phone = '9656470990' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Muaz Khan' OR (phone = '9026305812' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Yasir' OR (phone = '8418990037' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Moizul Haque' OR (phone = '9096375421' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Munazzam Hussain Khan' OR (phone = '9520006581' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nihal Mohammad' OR (phone = '8792908185' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Raghib Azeez' OR (phone = '8318237914' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saalik Qamar' OR (phone = '9153830757' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Safiur Rahman Nabeel' OR (phone = '7991984174' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saqib Kamal Falahi' OR (phone = '9369374208' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shakeeb Arslan' OR (phone = '9946292307' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Aslam Muzakkir' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Maaz Rahi' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Aamir' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nizam Mohammed' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zeeshan Akhtar Quasmi' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Maaz Shams' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'Jamia Millia Islamia' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'TABISH RUB' OR (phone = '9355254498' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jasola' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Tanveer' OR (phone = '8595177048' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jasola' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Aurangzeb' OR (phone = '9576499029' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jasola' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Junaid Ansari' OR (phone = '9810253281' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Jasola' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Ruman Owais Ansari' OR (phone = '9911462801' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'campus', membership_id = (SELECT id FROM portal_campuses WHERE name = 'JNU' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Salman Akhtar' OR (phone = '9718643868' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kanchankunj' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Yousuf Zafar' OR (phone = '9818825896' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kanchankunj' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'UMAR FAROOQ' OR (phone = '7678421613' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kanchankunj' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Amir Danish' OR (phone = '9650033478' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kanchankunj' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Kashif Zafar' OR (phone = '7303539252' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kanchankunj' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Muzzammil' OR (phone = '7827862820' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kanchankunj' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'JUNAID' OR (phone = '9205825501' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kardampuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Anas' OR (phone = '9315991985' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kardampuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ali' OR (phone = '8929304337' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kardampuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Azimushshan Alam' OR (phone = '9971679234' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Kardampuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rihan' OR (phone = '8958896258' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Karol Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Altamash Faruqi' OR (phone = '9175949717' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Loni' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rikaz Ahmad' OR (phone = '8595177695' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Loni' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zubair Mirza' OR (phone = '7982059719' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Mahipalpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Sufiyan' OR (phone = '9118611409' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Sameer' OR (phone = '9911792432' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Shahadat' OR (phone = '8595734510' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Kamran' OR (phone = '8882767670' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Owais' OR (phone = '9891707869' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Rehan' OR (phone = '9810395271' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Hamza' OR (phone = '7503724724' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Bilal' OR (phone = '8700817951' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rehan' OR (phone = '8447647512' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MD AAMIR ANSARI' OR (phone = '8920965424' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'GULNAWAZ' OR (phone = '8766331320' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD KASHIF' OR (phone = '8901529623' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'DILNAWAZ' OR (phone = '9368371819' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nabi Karim' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MD AQIB' OR (phone = '8864920379' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'New Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Hasan' OR (phone = '8742969049' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'New Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shahzan' OR (phone = '9582394055' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'New Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shuaib' OR (phone = '9821457985' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Nihal Vihar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shajar Zeeshan' OR (phone = '8178264698' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Okhla Village' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md. Hanzala Khan' OR (phone = '6299686690' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Okhla Village' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nasiruddin' OR (phone = '9911321490' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Okhla Village' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md. Alfaz Khan' OR (phone = '8294239262' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Okhla Village' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Maaz Khan' OR (phone = '9026305812' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Okhla Village' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shujauddin' OR (phone = '9540487494' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Okhla Village' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Touseef Ahmed' OR (phone = '8561896702' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Arshad' OR (phone = '9953273789' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Arsalan' OR (phone = '8585930992' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Shuaib' OR (phone = '9899868113' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Azim' OR (phone = '7827432427' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Zaki' OR (phone = '9811559012' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Muhammad Sarfaraz' OR (phone = '9312881862' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Muneeruddin' OR (phone = '8130069061' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shamshad Ali' OR (phone = '8384043152' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD FARDIN ANSARI' OR (phone = '9654139368' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD ZEESHAN SAIFI' OR (phone = '9717385640' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MD RAZI ANSARI' OR (phone = '9958773370' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Old Mustafabad' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD SAKIB MALIK' OR (phone = '9315197285' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Pasonda' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Museer Alam' OR (phone = '9759761427' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Raghubir Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdullah Ansari' OR (phone = '7019665934' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Raghubir Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Aftab Husain' OR (phone = '9310762458' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Saket' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'SK Mohammad Haneef' OR (phone = '9704020978' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Hafees' OR (phone = '9315051747' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Affan' OR (phone = '9588507087' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Aman Ali' OR (phone = '9318432034' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Monis Khan' OR (phone = '8368263645' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Shadman' OR (phone = '7827884453' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Aleem' OR (phone = '8595874714' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Azeem' OR (phone = '8882316765' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Seemapuri' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Moin Khan' OR (phone = '7840865278' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shahdara' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zainul Abideen' OR (phone = '9639069117' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'TAHA MUJAHID' OR (phone = '9871985570' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abdul Munim Naseh' OR (phone = '9169300711' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Abidullah Mohsin' OR (phone = '9718859695' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ali Ansari' OR (phone = '8882320268' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Athar Ali' OR (phone = '9711824264' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Haris Neyazi' OR (phone = '8882837767' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohammad Tausif' OR (phone = '9891226461' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Obaidurrehman Naufal' OR (phone = '7906474636' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Omair Afzal' OR (phone = '7827378127' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rehan Mohammad Ali' OR (phone = '9555506460' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Rizwan Ahmad' OR (phone = '9891935815' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saad Mansoor' OR (phone = '9205116970' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Wamiq Ur Rab' OR (phone = '8860584321' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Waqqas Hikmatyar' OR (phone = '8826631198' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Wasiullah Ahmad' OR (phone = '9873914915' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Zaeem Ahmad Mansoori' OR (phone = '9354809443' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'PERVEZ MUSHARRAF' OR (phone = '9213862966' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHAMMAD UMAR IQBAL' OR (phone = '' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'HASHIM AZMI' OR (phone = '9310663871' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Shaheen Bagh' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'MOHD NOMAN' OR (phone = '7979880550' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'shakurpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Ateeq' OR (phone = '9151241734' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'shakurpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Danish' OR (phone = '6387913305' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Usmanpur' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Anas' OR (phone = '8750760644' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vijay Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saalik Islam' OR (phone = '9538460730' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Farhan Beg' OR (phone = '9717955232' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Junaid Beg' OR (phone = '9311062319' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Mayur Khan' OR (phone = '8076323682' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Sameer Khan' OR (phone = '9560487022' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Md Samiullah' OR (phone = '9798495476' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Mohd Haider Ali' OR (phone = '7503787636' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Nasid' OR (phone = '9650688903' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saddam Malik' OR (phone = '8447462951' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Saiyad Arman' OR (phone = '9911403205' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sarfaraz Khan' OR (phone = '8851222824' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Sartaj' OR (phone = '8882985087' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Uvaish Saifi' OR (phone = '7834994709' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'Yusuf Khan' OR (phone = '8882176206' AND phone IS NOT NULL AND phone != ''));
UPDATE portal_users SET membership_type = 'unit', membership_id = (SELECT id FROM portal_units WHERE name = 'Vikas Nagar' LIMIT 1) WHERE (CONCAT_WS(' ', first_name, middle_name, last_name) = 'RIYAJ ANSARI' OR (phone = '9821836802' AND phone IS NOT NULL AND phone != ''));
